### ISSUE TITLE
정말 죄송합니다

### ISSUE THREAD

**Issue by avocad5** [thoratica/remote-kakao#1]
제가 어제 EntryBlockers에서 나가기 위해서 (제가 별로 활동을 안하는것 같아서 나가려고 했습니다)
delete(?) 버튼같은걸 눌렀었습니다
저는 그게 탈퇴버튼인줄 알고 누른것이었는데
인터넷에서 찾아보니까 EntryBlockers자체를 아예 삭제해버리는 버튼인것같더라구요...
그래서 EntryBlockers에 계시던 모든분들께 죄송하다는 말을 전하고 싶었는데
누가 EntryBlockers에 있었는지 정확히 기억이 나지 않고,
그분들과 소통을 할 방법을 모르겠어서 여기다가 이슈를 남깁니다 ㅠㅠ

혹시 가능하다면
thoratica님이 EntryBlockers에 계시던 다른 분들에게도
이 사실을 전해주실수있을까요?

다시한번 죄송합니다.

**Comment by thoratica** [comment]
엉뚱한 곳에 이슈 열지 말고 개인적으로 연락해주세요

**Comment by avocad5** [comment]
죄송합니다
어디로 연락하면 되나요? thoratica님 디스코드를 잘 몰라서요

**Comment by thoratica** [comment]
> 죄송합니다
> 어디로 연락하면 되나요? thoratica님 디스코드를 잘 몰라서요
> 

Android#0011
